global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Quiry Discord Bot
  - job_name: 'quiry-bot'
    static_configs:
      - targets: ['host.docker.internal:8083']
    scrape_interval: 5s
    metrics_path: /metrics

  # Quiry Consumer
  - job_name: 'quiry-consumer'
    static_configs:
      - targets: ['host.docker.internal:8084']
    scrape_interval: 5s
    metrics_path: /metrics

  # Quiry Indexer
  - job_name: 'quiry-indexer'
    static_configs:
      - targets: ['host.docker.internal:8085']
    scrape_interval: 5s
    metrics_path: /metrics

  # ElasticSearch (removed - doesn't have prometheus metrics endpoint)
  # - job_name: 'elasticsearch'
  #   static_configs:
  #     - targets: ['elasticsearch:9200']
  #   metrics_path: /_prometheus/metrics
  #   scrape_interval: 30s

  # Kafka JMX Exporter (removed - not configured)
  # - job_name: 'kafka'
  #   static_configs:
  #     - targets: ['kafka:9308']
  #   scrape_interval: 30s

