[package]
name = "Quiry"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.12", features = ["client", "gateway", "model", "builder"] }
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
dotenv = "0.15"
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.145"
